version: "3.7"
services:
  database:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    restart: always
    env_file:
      - .env
    volumes: 
      - kmo:/data/db
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
    - "8080:8080"
volumes:
  kmo: